/**
 * Test Extreme Dynamic NLP - All Question Formats
 * Tests the completely flexible semantic understanding system
 */

import { extractIntent } from './services/dynamicIntentExtractor.js';

async function testExtremeDynamicNLP() {
  console.log('🚀 Testing EXTREME Dynamic NLP - All Question Formats\n');
  
  // Test flow selection with maximum flexibility
  console.log('=== EXTREME FLOW SELECTION TESTS ===');
  const flowTests = [
    // Home visit - ALL possible formats
    'i want to select home visit',
    'can you select home visit', 
    'i have to select home visit',
    'could you book appointment for home visit',
    'doctor should come to my house',
    'I prefer someone comes to me',
    'medical visit at home please',
    'need a house call',
    'can doctor visit my residence?',
    'want medical professional at home',
    'home visit sounds good',
    'let\'s go with home visit',
    'what about home visit?',
    'home visit please',
    'just home visit',
    'home visit would be better',
    'leaning towards home visit',
    'maybe home visit',
    'probably home visit',
    'I guess home visit',
    'thinking home visit',
    'home visit vs center visit',
    'between home and center',
    'home visit or diagnostic?',
    'should I choose home visit?',
    'is home visit available?',
    'do you have home visit option?',
    'home visit for me please',
    'get someone to come home',
    'send doctor to home',
    'medical appointment at home',
    'in-home medical visit',
    'doctor at my place',
    'medical house call',
    
    // Center visit - ALL possible formats
    'i want to select diagnostic center',
    'can you book diagnostic center',
    'i need to visit center',
    'I\'ll go to a center',
    'need to go somewhere medical',
    'prefer to visit a clinic',
    'can I visit the diagnostic facility?',
    'want to go to medical place',
    'should I go to a lab?',
    'need to travel for medical test',
    'diagnostic center sounds good',
    'let\'s choose diagnostic center',
    'what about diagnostic center?',
    'diagnostic center please',
    'just diagnostic center',
    'diagnostic center would be better',
    'leaning towards diagnostic center',
    'maybe diagnostic center',
    'probably diagnostic center',
    'I guess diagnostic center',
    'thinking diagnostic center',
    'center visit vs home visit',
    'between center and home',
    'center or home visit?',
    'should I choose center?',
    'is center available?',
    'do you have center option?',
    'center visit for me please',
    'go to medical facility',
    'visit diagnostic place',
    'medical center appointment',
    'go to healthcare facility',
    'travel for medical test',
    
    // Out of scope
    'What time is it?',
    'Who is the president?',
    'How is the weather?',
    'Tell me a joke',
    'What\'s for dinner?'
  ];

  for (const test of flowTests) {
    try {
      const result = await extractIntent(test, 'flow_selection');
      console.log(`"${test}" → ${result}`);
    } catch (error) {
      console.log(`"${test}" → ERROR: ${error.message}`);
    }
  }

  console.log('\n=== EXTREME CENTER SELECTION TESTS ===');
  const centerTests = [
    // Healthcare - ALL possible formats
    'i want to select healthcare',
    'can you choose healthcare',
    'i have to pick healthcare',
    'could you book healthcare',
    'healthcare sounds good',
    'let\'s go with healthcare',
    'what about healthcare?',
    'healthcare please',
    'the first one',
    'option 1',
    'the healthcare center',
    'just healthcare',
    'healthcare would be better',
    'leaning towards healthcare',
    'maybe healthcare',
    'probably healthcare',
    'I guess healthcare',
    'thinking healthcare',
    'healthcare vs city lab',
    'between healthcare and medplus',
    'healthcare or city lab?',
    'should I choose healthcare?',
    'is healthcare good?',
    'what about healthcare?',
    'healthcare for me please',
    'that healthcare place',
    'healthcare sounds fine',
    'I\'d prefer healthcare',
    'helthcare', // typo
    'HC', // abbreviation
    'the first option',
    'number 1',
    '1st option',
    'the top one',
    
    // City Lab - ALL possible formats
    'i want to select city lab',
    'can you choose city lab',
    'i have to pick city lab',
    'could you book city lab',
    'city lab seems good',
    'let\'s choose city lab',
    'what about city lab?',
    'city lab please',
    'the second one',
    'option 2',
    'the middle option',
    'city lab diagnostics',
    'just city lab',
    'city lab would be better',
    'leaning towards city lab',
    'maybe city lab',
    'probably city lab',
    'I guess city lab',
    'thinking city lab',
    'city lab vs healthcare',
    'between city lab and medplus',
    'city lab or medplus?',
    'should I choose city lab?',
    'is city lab available?',
    'what about city lab?',
    'city lab for me please',
    'that city lab place',
    'city lab sounds fine',
    'I\'d prefer city lab',
    'city lab', // simple
    'CL', // abbreviation
    'the middle one',
    'number 2',
    '2nd option',
    'the one in middle',
    
    // MedPlus - ALL possible formats
    'i want to select medplus',
    'can you choose medplus',
    'i have to pick medplus',
    'could you book medplus',
    'medplus looks good',
    'let\'s go with medplus',
    'what about medplus?',
    'medplus please',
    'the third one',
    'option 3',
    'the closest one',
    'the nearest',
    'which is closest?',
    'medplus lab',
    'just medplus',
    'medplus would be better',
    'leaning towards medplus',
    'maybe medplus',
    'probably medplus',
    'I guess medplus',
    'thinking medplus',
    'medplus vs healthcare',
    'between medplus and city lab',
    'medplus or city lab?',
    'should I choose medplus?',
    'is medplus good?',
    'what about medplus?',
    'medplus for me please',
    'that medplus place',
    'medplus sounds fine',
    'I\'d prefer medplus',
    'medpls', // typo
    'MP', // abbreviation
    'the last one',
    'number 3',
    '3rd option',
    'the nearest one',
    
    // Out of scope
    'What time is it?',
    'Tell me a joke',
    'How are you?'
  ];

  for (const test of centerTests) {
    try {
      const result = await extractIntent(test, 'center_selection');
      console.log(`"${test}" → ${result}`);
    } catch (error) {
      console.log(`"${test}" → ERROR: ${error.message}`);
    }
  }

  console.log('\n=== EXTREME TIME SELECTION TESTS ===');
  const timeTests = [
    // 7 AM - ALL possible formats
    'i want to select 7 am',
    'can you choose 7 am',
    'i have to pick 7 am',
    'could you book 7 am',
    '7 am sounds good',
    'let\'s go with 7 am',
    'what about 7 am?',
    '7 am please',
    'the first one',
    'option 1',
    'seven in the morning',
    '7 o\'clock',
    'early morning',
    'the earliest',
    'first slot',
    '7:00',
    '7am',
    '7 a.m.',
    'seven',
    'around 7',
    'about 7',
    'sometime 7',
    '7ish',
    'earliest slot',
    'first available',
    'early slot',
    'start of day',
    'morning time',
    'after sunrise',
    '7 in morning',
    'seven o\'clock',
    '7 hundred hours',
    '0700 hours',
    '7 in the am',
    'seven am',
    'the 7 o\'clock slot',
    '7 o\'clock appointment',
    'early time',
    'first time slot',
    '7:00 am',
    '07:00',
    '7 in the morning',
    'seven in am',
    '7am appointment',
    'the 7am slot',
    'early 7am',
    '7am sharp',
    
    // 8 AM - ALL possible formats
    'i want to select 8 am',
    'can you choose 8 am',
    'i have to pick 8 am',
    'could you book 8 am',
    '8 am sounds good',
    'let\'s choose 8 am',
    'what about 8 am?',
    '8 am please',
    'the second one',
    'option 2',
    'eight in the morning',
    '8 o\'clock',
    'mid-morning',
    'the middle slot',
    '8:00',
    '8am',
    '8 a.m.',
    'eight',
    'around 8',
    'about 8',
    'sometime 8',
    '8ish',
    'middle slot',
    'second available',
    'mid time',
    'center of day',
    '8 in morning',
    'eight o\'clock',
    '8 hundred hours',
    '0800 hours',
    '8 in the am',
    'eight am',
    'the 8 o\'clock slot',
    '8 o\'clock appointment',
    'mid time slot',
    '8:00 am',
    '08:00',
    '8 in the morning',
    'eight in am',
    '8am appointment',
    'the 8am slot',
    'mid 8am',
    '8am sharp',
    
    // 9 AM - ALL possible formats
    'i want to select 9 am',
    'can you choose 9 am',
    'i have to pick 9 am',
    'could you book 9 am',
    '9 am sounds good',
    'let\'s go with 9 am',
    'what about 9 am?',
    '9 am please',
    'the third one',
    'option 3',
    'nine in the morning',
    '9 o\'clock',
    'late morning',
    'the latest',
    'last slot',
    '9:00',
    '9am',
    '9 a.m.',
    'nine',
    'around 9',
    'about 9',
    'sometime 9',
    '9ish',
    'latest slot',
    'last available',
    'late time',
    'end of morning',
    '9 in morning',
    'nine o\'clock',
    '9 hundred hours',
    '0900 hours',
    '9 in the am',
    'nine am',
    'the 9 o\'clock slot',
    '9 o\'clock appointment',
    'late time slot',
    '9:00 am',
    '09:00',
    '9 in the morning',
    'nine in am',
    '9am appointment',
    'the 9am slot',
    'late 9am',
    '9am sharp',
    
    // Invalid times
    '6 pm',
    '10 am',
    '5 pm',
    'noon',
    'midnight',
    '2 pm',
    '11 am',
    '3 pm',
    '4 pm',
    '1 pm',
    '12 pm',
    '12 am',
    '6 am',
    '5 am',
    '10 pm',
    '11 pm',
    '1 am',
    '2 am',
    '3 am',
    '4 am',
    '7 pm',
    '8 pm',
    '9 pm',
    'afternoon',
    'evening',
    'night',
    'dawn',
    'dusk',
    'sunrise',
    'sunset',
    
    // Out of scope
    'What time is it?',
    'Is it lunch time yet?',
    'When should I eat?'
  ];

  for (const test of timeTests) {
    try {
      const result = await extractIntent(test, 'time_selection');
      console.log(`"${test}" → ${result}`);
    } catch (error) {
      console.log(`"${test}" → ERROR: ${error.message}`);
    }
  }

  console.log('\n=== EXTREME DISTANCE CONFIRMATION TESTS ===');
  const distanceTests = [
    // Acceptance - ALL possible formats
    'i want to accept',
    'can you proceed',
    'i have to accept',
    'could you continue',
    'that distance works',
    'sounds good',
    'let\'s continue',
    'that\'s fine',
    'no problem',
    'it\'s okay',
    'alright',
    'sure',
    'good',
    'perfect',
    'excellent',
    'that\'ll work',
    'I\'m fine with that',
    'that\'s acceptable',
    'let\'s do it',
    'go ahead',
    'proceed',
    'continue',
    'yeah that\'s fine',
    'mhm works for me',
    'I guess so',
    'probably fine',
    'happy with this',
    'satisfied',
    'if you don\'t mind',
    'please continue',
    'let\'s hurry',
    'for my schedule this works',
    'this is good for me',
    'I can do this',
    'no issues',
    'all good',
    'looks good',
    'seems fine',
    'works for me',
    'okay with this',
    'agree',
    'approved',
    'confirmed',
    'yes please',
    'definitely',
    'absolutely',
    'of course',
    'certainly',
    'by all means',
    'I\'m okay with it',
    'that\'s settled',
    'let\'s move on',
    'carry on',
    
    // Rejection - ALL possible formats
    'i want to reject',
    'can you choose another',
    'i have to change',
    'could you pick different',
    'that\'s too far',
    'too far for me',
    'not acceptable',
    'I don\'t like this',
    'that won\'t work',
    'find something else',
    'change this',
    'different one',
    'not good',
    'bad',
    'terrible',
    'unacceptable',
    'I can\'t do this',
    'this is inconvenient',
    'prefer something closer',
    'need a better option',
    'let\'s find another',
    'can we try again?',
    'nope too far',
    'nah find another',
    'maybe not',
    'thinking no',
    'frustrated by distance',
    'disappointed',
    'would you mind finding another?',
    'need to decide',
    'with my mobility this is hard',
    'given my situation this won\'t work',
    'this is difficult for me',
    'I have concerns',
    'not comfortable',
    'this is a problem',
    'this won\'t suit me',
    'I\'m not happy with this',
    'this doesn\'t work for me',
    'I\'d prefer not',
    'rather not',
    'I\'d rather find something else',
    'this isn\'t ideal',
    'not what I wanted',
    'this is not good',
    'I\'m not satisfied',
    'this is unacceptable',
    'I refuse',
    'I decline',
    'no thanks',
    'pass',
    'skip this',
    'next option',
    'alternative please',
    'something different',
    'other choice',
    'new option',
    
    // Out of scope
    'What is the capital of France?',
    'How far is the moon?',
    'What\'s the weather like?',
    'Tell me about yourself'
  ];

  for (const test of distanceTests) {
    try {
      const result = await extractIntent(test, 'distance_confirmation');
      console.log(`"${test}" → ${result}`);
    } catch (error) {
      console.log(`"${test}" → ERROR: ${error.message}`);
    }
  }

  console.log('\n🎉 EXTREME Dynamic NLP Testing Complete!');
  console.log('📝 The system now handles ANY possible way users can phrase questions!');
  console.log('🚀 Maximum flexibility achieved - no hardcoded patterns!');
}

// Run tests
testExtremeDynamicNLP().catch(console.error);
